on:
  push:
    branches:
    - master
    
  schedule:
  - cron: "0 6,12,18 * * *"
  
jobs:
  merge:
    name: Merge src to a file
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Merge and Commit files
        run: |
          cat ./src/Header.txt > ./all-in-one.txt
          cat ./src/ad.txt >> ./all-in-one.txt
          cat ./src/css-extended.txt >> ./all-in-one.txt
          cat ./src/url-blocking.txt >> ./all-in-one.txt
          cat ./src/whitelist.txt >> ./all-in-one.txt
          cat ./src/malware.txt >> ./all-in-one.txt
          echo "! End" >> ./all-in-one.txt
          git version
          sleep 1
          git config --global user.name "AGDDoS-bot"
          git config --global user.email "3356136957@qq.com"
          sleep 1
          git pull
          git add .
          git commit --allow-empty -m "update: `date '+%Y-%m-%d %H:%M:%S'` all-in-one [skip ci]"
          sleep 1
          git push
          echo Success!
